config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'
  get 'home/profile' => 'home#profile'
  get 'home/created' => 'home#created'

  resources :workout_plans do
    member do
      get 'dashboard'
      post 'follow'
      post 'delete_follow'
    end
    resources :workouts
  end

  resources :workouts do
    member do
      get 'dashboard'
      post 'complete'
    end
    resources :workout_sets do
      member do
        post 'complete'
        post 'duplicate'
      end
    end
  end

end

app/models/workout.rb
class Workout < ActiveRecord::Base
  belongs_to :workout_plan
  has_many :workout_sets
  has_many :completed_workouts
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update]

  def index
    @workout = Workout.where(workout_plan_id: params[:workout_plan_id])
    @workout_plan = WorkoutPlan.find(params[:workout_plan_id])
    @follow_status = Follow.where(user: current_user, workout_plan: @workout_plan).present?
    if current_user
      @completed = CompletedWorkout.where(workout_id: @workout, user_id: current_user.id)
    end
  end

  def show
    @workout = Workout.find(params[:workout_id])
  end

  def new
    workout_plan = WorkoutPlan.find(params[:workout_plan_id])
    @workout = workout_plan.workouts.build
  end

  def create
    workout_plan = WorkoutPlan.find(params[:workout_plan_id])
    @workout = workout_plan.workouts.create(workout_params)
    if @workout.save
      flash[:success] = 'Your Workout Was created'
      redirect_to dashboard_workout_plan_path(workout_plan)
    else
      render :new
    end
  end

  def edit
    @workout = Workout.find(params[:id])
  end

  def update
    @workout = Workout.find(params[:id])
    if @workout.update(workout_params)
      flash[:success] = 'Your Workout was updated successfully'
      redirect_to dashboard_workout_plan_path(@workout.workout_plan)
    else
      render :edit
    end
  end

  def destroy
    @workout = Workout.find(params[:id])
    @workout_sets = WorkoutSet.where(workout_id: @workout)
    @workout_sets.each do |workout_set|
      WorkoutSet.find(workout_set.id).destroy
    end
    Workout.find(@workout).destroy
    flash[:success] = 'Successfully deleted'
    redirect_to dashboard_workout_plan_path(@workout.workout_plan)
  end

  def complete
    @workout = Workout.find(params[:id])
    if CompletedWorkout.where(user: current_user, workout: @workout).present?
      flash[:danger] = "You have already completed #{@workout.name}"
      redirect_to workout_plan_workouts_path(@workout.workout_plan) # send suser back to where they were came from
    else
      CompletedWorkout.create(completed: params[:completed], user: current_user, workout: @workout)
      flash[:success] = "Completed #{@workout.name}"
      redirect_to workout_plan_workouts_path(@workout.workout_plan)# send suser back to where they were came from
    end
  end

  def dashboard
    @workout = Workout.find(params[:id])
    @workout_sets = WorkoutSet.where(workout: @workout)
  end

  private

  def workout_params
    params.require(:workout).permit(:name, :day, :description)
  end

  def require_same_user
    @workout = Workout.find(params[:id])
    workout_plan = WorkoutPlan.find(@workout.workout_plan)
    if current_user != workout_plan.user
      flash[:danger] = 'You can only edit your own workouts'
      redirect_to workout_path
    end
  end
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/workouts/dashboard.html.erb
<div class="dashboard-container margin-top-25px padding-bottom-25px">
  <%= link_to 'Back to workouts',dashboard_workout_plan_path(@workout.workout_plan_id) %>
  <br />
  <span class="section-title"><%= @workout.name %> Sets</span>
  <br />
  <table class="margin-25px">
    <tr>
      <th>Name</th>
      <th>Amount</th>
      <th>Rep Type</th>
      <th>Description</th>
      <th>Edit</th>
      <th>Duplicate</th>
      <th>Delete</th>
    </tr>
    <% @workout_sets.each do |w| %>
      <tr>
        <td><%= w.name %></td>
        <td><%= w.amount %></td>
        <td><%= w.rep_type %></td>
        <td><%= w.description %></td>
        <td>
          <%= link_to edit_workout_workout_set_path(@workout.id ,w.id) do %>
            <%= image_tag('edit_dark_icon.png', style: 'width: 20px;') %>
          <% end %>
        </td>
        <td>
          <%= link_to duplicate_workout_workout_set_path(@workout.id, w.id), method: :post do %>
            <%= image_tag('copy_icon.png', style: 'width: 20px;') %>
          <% end %>
        </td>
        <td>
          <%= link_to workout_workout_set_path(@workout.id, w.id), method: :delete, data: { confirm: "Are you sure?" } do %>
            X
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
  <%= link_to "Add Set", new_workout_workout_set_path(@workout.id)%>
</div>

app/views/workouts/edit.html.erb
<div class="content-container">
  <div class="form">
    <%= form_for @workout do |f| %>
    <h1 class="section-title">Creating workouts for this particular plan</h1>
    <div class="form-first-row">
      <div class="form-label-group">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>
      <div class="form-label-group">
        <%= f.label :day %>
        <%= f.text_field :day %>
      </div>
    </div>
    <div class="form-second-row">
      <div class="form-label-group">
        <%= f.label :description %>
        <%= f.text_area :description, rows: 10 %>
      </div>
    </div>
    <div class="form-submission">
      <%= f.submit class: 'primary-button' %>
    </div>
    <% end %>
  </div>
</div>  

app/views/workouts/index.html.erb
<div class="content-container">
  <div class="container plans-container">
    <div class="split-container">
      <span class="section-title"><%= @workout_plan.name %></span>
      <div class="workout-image">
        <%= image_tag(@workout_plan.picture.url) if @workout_plan.picture? %>
      </div>
      <span class="workout-summary"><%= @workout_plan.summary %></span>
      <span class="workout-description"><%= @workout_plan.description %></span>
      <span class="workout-summary">By: <%= @workout_plan.user.email %></span>
      <% follower_amount = Follow.where(workout_plan: @workout_plan).length %>
      <% if follower_amount == 1 %>
        <span class="workout-stats"><%= follower_amount %> Follower</span>
      <% else %>
        <span class="workout-stats"><%= follower_amount%> Followers</span>
      <% end %>
      <% if @follow_status %>
        <div class="secondary-button-div">
          Following
        </div>
      <% else %>
        <%= link_to follow_workout_plan_path(@workout_plan, follow: true), class: 'primary-button', method: :post do %>
          Follow
        <% end %>
      <% end %>
    </div>
    <div class="split-container">

      <% workout_count = Workout.where(workout_plan: @workout_plan)%>
      <% if @follow_status %>
        <span class="workout-stats"><%= @completed.count %> of <%= workout_count.length %> Workouts completed</span>
      <% else %>
        <span class="workout-stats"><%= workout_count.length %> Workouts</span>
      <% end %>
      <% @workout.each do |workout_day| %>
      <% if Follow.where(user: current_user, workout_plan: @workout_plan).present? || @workout_plan.user == current_user %>
        <!-- Completed workout -->
        <% if CompletedWorkout.where(user: current_user, workout: workout_day).present? %>
            <%= link_to workout_workout_sets_path(workout_day) do %>
              <div class="workout-day-box">
                <div class="workout-box-left">
                  <div class="workout-day">
                    Day <%= workout_day.day %>
                  </div>
                  <div class="workout-name">
                    <%= workout_day.name %>
                  </div>
                </div>
                <div class="workout-box-status">
                  ✓
                </div>
              </div>
            <% end %>
          <!-- Uncompleted workout -->
          <% else %>
            <%= link_to workout_workout_sets_path(workout_day) do %>
              <div class="workout-day-box workout-day-box-uncompleted">
                <div class="workout-box-left">
                  <div class="workout-day">
                    Day <%= workout_day.day %>
                  </div>
                  <div class="workout-name">
                    <%= workout_day.name %>
                  </div>
                </div>
                <div class="workout-box-status workout-box-status-uncompleted">
                  ✓
                </div>
              </div>
            <% end %>
          <% end %>
        <!-- Not following workout -->
        <% else %>
          <div class="workout-day-box workout-day-box-uncompleted">
            <div class="workout-box-left">
              <div class="workout-day">
                Day <%= workout_day.day %>
              </div>
              <div class="workout-name">
                <%= workout_day.name %>
              </div>
            </div>
            <div class="workout-box-status workout-box-status-uncompleted">
              <%= image_tag('lock.png') %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/workouts/new.html.erb
<div class="content-container">
  <div class="form">
    <%= form_for ([@workout.workout_plan, @workout]) do |f| %>
    <h1 class="section-title">Creating workouts for this particular plan</h1>
    <div class="form-first-row">
      <div class="form-label-group">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>
      <div class="form-label-group">
        <%= f.label :day %>
        <%= f.text_field :day %>
      </div>
    </div>
    <div class="form-second-row">
      <div class="form-label-group">
        <%= f.label :description %>
        <%= f.text_area :description, rows: 10 %>
      </div>
    </div>
    <div class="form-submission">
      <%= f.submit class: 'primary-button' %>
    </div>
    <% end %>
  </div>
</div>  

app/views/workouts/show.html.erb
<h1>This particular workout</h1>
<%=  %>