config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'
  get 'home/profile' => 'home#profile'
  get 'home/created' => 'home#created'

  resources :workout_plans do
    member do
      get 'dashboard'
      post 'follow'
      post 'delete_follow'
    end
    resources :workouts
  end

  resources :workouts do
    member do
      get 'dashboard'
      post 'complete'
    end
    resources :workout_sets do
      member do
        post 'complete'
        post 'duplicate'
      end
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def profile
    @following = Follow.where(user: current_user.id).reverse
  end

  def created
    @workout_plans = WorkoutPlan.where(user: current_user).reverse
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/created.html.erb
<div class="content-container">
  <div class="container plans-container">
    <div class="split-container">
      <div class="crumbs-link">
        <%= link_to 'Following', home_profile_path %> | <%= link_to 'Created', home_created_path, class: 'crumbs-active' %> | <%= link_to 'Profile', edit_user_registration_path %>
      </div>
      <h1 class="section-title">Your created plans</h1>
      <% if @workout_plans.length < 1 %>
        <p class="primary-copy">You have not created any plans.</p>
        <%= link_to 'Create Plan', new_workout_plan_path, class: 'primary-button' %>
      <% else %>
        <% @workout_plans.each do |plan| %>
          <div class="plan-container">
            <div class="plan-image">
              <%= image_tag(plan.picture.url) if plan.picture? %>
            </div>
            <div class="plan-content">
              <div class="plan-description">
                <p><%= plan.description %></p>
              </div>
              <div class="plan-cta">
                <span class="plan-title"><%= link_to plan.name, workout_plan_workouts_path(plan) %></span>
                <%= link_to dashboard_workout_plan_path(plan), class: 'plan-follow-button' do %>
                  Edit
                <% end %>
                <%= link_to workout_plan_path(plan), class: 'plan-follow-button unfollow-button', method: :delete, data: { confirm: "Are you sure?" } do %>
                  Delete
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="split-container">
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="container">
  <div class="hero">
  </div>
  <div class="home-info-section">
    <div class="how-it-works">
      <span class="how-it-works-copy">How it works</span>
      <div class="how-it-works-border"></div>
    </div>
    <%= image_tag('lock.png') %>
    <div class="how-it-works">
      <span class="how-it-works-copy-md">Follow or Create <br /> Workouts</span>
    </div>
    <%= image_tag('lock.png', class: "padding-top-60px") %>
    <div class="how-it-works">
      <span class="how-it-works-copy-md">Follow plans created <br /> by the community</span>
    </div>
    <span class="how-it-works-copy-body">
      Use our simple app on<br /> the go to complete workout <br /> plans that suit you
    </span>
    <span class="how-it-works-link padding-top-10px">
      Lose Hale now
    </span>
    <%= image_tag('lock.png', class: "padding-top-60px") %>
    <div class="how-it-works">
      <span class="how-it-works-copy-md">Create your own <br /> plan with our editor</span>
    </div>
    <span class="how-it-works-copy-body">
      Use our simple app on<br /> the go to complete workout <br /> plans that suit you
    </span>
    <span class="how-it-works-link padding-top-10px">
      Lose Hale now
    </span>
  </div>



  <div class="home-image-section">
    <div class="home-image-row">
      <div class="box-1">
        <div class="home-box-overlay">
          <span class="home-box-cta">Most popular</span>
          <span class="home-box-copy">See the most popular and highest ranked plans</span>
        </div>
      </div>
      <div class="box-2">
        <div class="home-box-overlay">
          <span class="home-box-cta">Highest Ranked</span>
          <span class="home-box-copy">See the most popular and highest ranked plans</span>
        </div>
      </div>
    </div>
    <div class="home-image-row">
      <div class="box-3">
        <div class="home-box-overlay">
          <span class="home-box-cta">Core workouts</span>
          <span class="home-box-copy">See the most popular and highest ranked plans</span>
        </div>
      </div>
      <div class="box-4">
        <div class="home-box-overlay">
          <span class="home-box-cta">Stamina Workouts</span>
          <span class="home-box-copy">See the most popular and highest ranked plans</span>
        </div>
      </div>
    </div>
  </div>



  <div class="home-final-cta-section padding-100px">
    <span class="home-large-cta-copy">Join Now</span>
    <span class="how-it-works-copy-body padding-top-10px">
      Use our simple app on<br /> the go to complete workout <br /> plans that suit you
    </span>
    <div class="home-button margin-top-25px">Sign Up</div>
  </div>
</div>

app/views/home/profile.html.erb
<div class="content-container">
  <div class="container plans-container">
    <div class="split-container">
      <div class="crumbs-link">
        <%= link_to 'Following', home_profile_path, class: 'crumbs-active' %> | <%= link_to 'Created', home_created_path %> | <%= link_to 'Profile', edit_user_registration_path %>
      </div>
      <h1 class="section-title">Your plans</h1>
      <% if @following.length < 1 %>
        <p class="primary-copy">You arent following any plans</p>
        <%= link_to 'Find Plans', workout_plans_path, class: 'primary-button' %>
      <% else %>
        <% @following.each do |follow| %>
          <%= link_to workout_plan_workouts_path(follow.workout_plan) do %>
            <div class="plan-container">
              <div class="plan-image">
                <%= image_tag(follow.workout_plan.picture.url) if follow.workout_plan.picture? %>
              </div>
              <div class="plan-content">
                <div class="plan-name">
                  <span><%= follow.workout_plan.name %></span>
                </div>
                <div class="plan-description">
                  <%= follow.workout_plan.description %>
                </div>
                <div class="plan-cta">
                  <%= link_to delete_follow_workout_plan_path(follow.id), class: 'plan-follow-button unfollow-button', method: :post do %>
                  Unfollow
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
    <div class="split-container">
    </div>
  </div>
</div>