config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'
  get 'home/profile' => 'home#profile'
  get 'home/created' => 'home#created'

  resources :workout_plans do
    member do
      get 'dashboard'
      post 'follow'
      post 'delete_follow'
    end
    resources :workouts
  end

  resources :workouts do
    member do
      get 'dashboard'
      post 'complete'
    end
    resources :workout_sets do
      member do
        post 'complete'
        post 'duplicate'
      end
    end
  end

end

app/models/workout_set.rb
class WorkoutSet < ActiveRecord::Base
  belongs_to :workout
end

app/controllers/workout_sets_controller.rb
class WorkoutSetsController < ApplicationController
  before_filter :set_intializers, only: [:index]

  def index
  end

  def new
    workout = Workout.find(params[:workout_id])
    @workout_set = workout.workout_sets.build
  end

  def create
    workout = Workout.find(params[:workout_id])
    @workout_set = workout.workout_sets.create(workout_set_params)
    if @workout_set.save
      flash[:success] = 'Your Workout set Was created'
      redirect_to dashboard_workout_path(workout)
    else
      render :new
    end
  end

  def duplicate
    @workout_set = WorkoutSet.find(params[:id]).dup
    if @workout_set.save
      flash[:success] = 'Set was duplicated'
      redirect_to dashboard_workout_path(params[:workout_id])
    else
      flash[:danger] = 'Set could not be duplicated'
      redirect_to dashboard_workout_path(params[:workout_id])
    end
  end

  def edit
    @workout_set = WorkoutSet.find(params[:id])
  end

  def update
    @workout_set = WorkoutSet.find(params[:id])
    if @workout_set.update(workout_set_params)
      flash[:success] = 'Your Workout was updated successfully'
      redirect_to dashboard_workout_path(@workout_set.workout)
    else
      render :edit
    end
  end

  def destroy
    @workout_set = WorkoutSet.find(params[:id])
    WorkoutSet.find(@workout_set).destroy
    flash[:success] = 'Successfully deleted'
    redirect_to dashboard_workout_path(@workout_set.workout)
  end

  def complete
    CompletedSet.create(completed: params[:completed], user: current_user, workout_set: @workout_set)
    flash[:success] = "You have completed the #{@workout_set.name} set"
    redirect_to workout_workout_sets_path(@workout_set.workout)
  end

  private

  def workout_set_params
    params.require(:workout_set).permit(:name, :rep_type, :amount, :description)
  end

  def set_intializers
    @workout = Workout.find(params[:workout_id])
    @workout_set = WorkoutSet.where(workout_id: @workout)
    @workout_plan = WorkoutPlan.find(@workout.workout_plan)
    @workout_plan_days = Workout.where(workout_plan_id: @workout_plan)
  end

  def require_same_user
    workout = Workout.find(@workout_set.workout)
    if current_user != workout.user
      flash[:danger] = 'You can only edit your own workouts'
      redirect_to workout_path
    end
  end
end

app/helpers/workout_sets_helper.rb
module WorkoutSetsHelper
end

app/views/workout_sets/edit.html.erb
<div class="content-container">
  <div class="form">
    <%= form_for ([@workout_set.workout, @workout_set]) do |f| %>
    <h1 class="section-title">Edit set for a workout</h1>
    <div class="form-first-row">
      <div class="form-label-group">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>
    </div>
    <div class="form-first-row">
      <div class="form-label-group">
        <%= f.label :rep_type %>
        <%= f.text_field :rep_type %>
      </div>
    </div>
    <div class="form-first-row">
      <div class="form-label-group">
        <%= f.label :amount %>
        <%= f.text_field :amount %>
      </div>
    </div>
    <div class="form-second-row">
      <div class="form-label-group">
        <%= f.label :description %>
        <%= f.text_area :description, rows: 10 %>
      </div>
    </div>
    <div class="form-submission">
      <%= f.submit class: 'primary-button' %>
    </div>
    <% end %>
  </div>
</div>

app/views/workout_sets/index.html.erb
<%= react_component('WorkoutSet', current_user: current_user, workout_set: @workout_set, workout: @workout, workout_plan: @workout_plan, workout_plan_days: @workout_plan_days)  %>
<div className="container">
  <div class="set-box-container-bottom">
    <div class="set-button-container">
      <%= link_to complete_workout_path(id: @workout.id, completed: true), class: '', method: :post do %>
        <div class="set-button set-button-completed">
          Complete
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/workout_sets/new.html.erb
<div class="content-container">
  <div class="form">
    <%= form_for ([@workout_set.workout, @workout_set]) do |f| %>
    <h1 class="section-title">Create set for a workout</h1>
    <div class="form-first-row">
      <div class="form-label-group">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>
    </div>
    <div class="form-first-row">
      <div class="form-label-group">
        <%= f.label :rep_type %>
        <%= f.text_field :rep_type %>
      </div>
    </div>
    <div class="form-first-row">
      <div class="form-label-group">
        <%= f.label :amount %>
        <%= f.text_field :amount %>
      </div>
    </div>
    <div class="form-second-row">
      <div class="form-label-group">
        <%= f.label :description %>
        <%= f.text_area :description, rows: 10 %>
      </div>
    </div>
    <div class="form-submission">
      <%= f.submit class: 'primary-button' %>
    </div>
    <% end %>
  </div>
</div>