config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'
  get 'home/profile' => 'home#profile'
  get 'home/created' => 'home#created'

  resources :workout_plans do
    member do
      get 'dashboard'
      post 'follow'
      post 'delete_follow'
    end
    resources :workouts
  end

  resources :workouts do
    member do
      get 'dashboard'
      post 'complete'
    end
    resources :workout_sets do
      member do
        post 'complete'
        post 'duplicate'
      end
    end
  end

end

app/models/workout_plan.rb
class WorkoutPlan < ActiveRecord::Base
  has_many :workouts
  belongs_to :user
  has_many :follows, dependent: :destroy
  mount_uploader :picture, PictureUploader
  validate :picture_size

  private

  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, 'Picture should be lass than 5MB')
    end
  end
end

app/controllers/workout_plans_controller.rb
class WorkoutPlansController < ApplicationController
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update]

  def index
    @workout_plans = WorkoutPlan.all.reverse
  end

  def show
    @workout_plan = WorkoutPlan.find(params[:id])
  end

  def new
    @workout_plan = WorkoutPlan.new
  end

  def create
    @workout_plan = WorkoutPlan.new(workout_plan_params)
    @workout_plan.user = current_user

    if @workout_plan.save
      flash[:success] = 'Your Workout Plan Was created'
      redirect_to dashboard_workout_plan_path(@workout_plan)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @workout_plan.update(workout_plan_params)
      flash[:success] = 'Your Workout Plan was updated successfully'
      redirect_to workout_plan_workouts_path(@workout_plan)
    else
      render :edit
    end
  end

  def destroy
    WorkoutPlan.find(params[:id]).destroy
    Follow.where(workout_plan: params[:id]).destroy_all
    flash[:success] = "Successfully deleted"
    redirect_to home_created_path
  end

  def follow
    @workout_plan = WorkoutPlan.find(params[:id])
    if Follow.where(user: current_user, workout_plan: @workout_plan).present?
      flash[:danger] = "You are already following the #{@workout_plan.name} plan."
      redirect_to :back  # send suser back to where they were came from
    else
      Follow.create(follow: params[:follow], user: current_user, workout_plan: @workout_plan)
      flash[:success] = "You are now following the #{@workout_plan.name} plan."
      redirect_to workout_plan_workouts_path(@workout_plan) 
    end
  end
# if Business.where(:user_id => current_user.id).present?
# if Business.exists?(user_id: current_user.id)
  def delete_follow
    @follow = Follow.find(params[:id])
    follow = @follow.delete
    if follow
      flash[:success] = "You have unfollowed this plan"
      redirect_to :back  # send suser back to where they were came from
    else
      flash[:danger] = "Your update could not be completed"
      redirect_to :back  # send suser back to where they were came from
    end
  end

  def dashboard
    @workout_plan = WorkoutPlan.find(params[:id])
    @workout = Workout.where(workout_plan: @workout_plan)
  end

  private

  def workout_plan_params
    params.require(:workout_plan).permit(:name, :description, :summary, :picture)
  end

  def require_same_user
    @workout_plan = WorkoutPlan.find(params[:id])
    if current_user != @workout_plan.user
      flash[:danger] = 'You can only edit your own workout plans'
      redirect_to workout_plans_path
    end
  end
end

app/helpers/workout_plans_helper.rb
module WorkoutPlansHelper
end

app/views/workout_plans/dashboard.html.erb
<div class="dashboard-container margin-top-25px padding-bottom-25px">
<span class="section-title"><%= @workout_plan.name %> plan</span>
<br />
<%= link_to "Edit", edit_workout_plan_path(@workout_plan) %>
<hr>

<table class="margin-25px">
  <tr>
    <th>Day</th>
    <th>Name</th>
    <th>Description</th>
    <th>Edit</th>
    <th>View Sets</th>
    <th>Delete</th>
  </tr>
  <% @workout.each do |w| %>
    <tr>
      <td><%= w.day %></td>
      <td><%= w.name %></td>
      <td><%= w.description %></td>
      <td>
        <%= link_to edit_workout_path(w.id) do %>
          <%= image_tag('edit_dark_icon.png', style: 'width: 20px;') %>
        <% end %>
      </td>
      <td>
        <%= link_to dashboard_workout_path(w.id) do %>
          <%= image_tag('view_icon.png', style: 'width: 25px;') %>
        <% end %>
      </td>
      <td>
        <%= link_to workout_path(w.id), method: :delete, data: { confirm: "Are you sure?" } do %>
          X
        <% end %>
      </td>
    </tr>
  <% end %>
</table>
  <%= link_to new_workout_plan_workout_path(@workout_plan) do %>
    New Workout
  <% end %>
</div>

app/views/workout_plans/edit.html.erb
<%= render 'partials/form' %>

app/views/workout_plans/index.html.erb
<div class="content-container">
  <h1 class="plan-type-heading">Most Popular</h1>
  <div class="container plans-container">
    <div class="split-container">
      <% @workout_plans.each do |plan| %>
        <%= link_to workout_plan_workouts_path(plan) do %>
          <div class="plan-container">
            <div class="plan-image">
              <%= image_tag(plan.picture.url) if plan.picture? %>
            </div>
            <div class="plan-content">
              <div class="plan-name">
                <span><%= plan.name %></span>
              </div>
              <div class="plan-description">
                <%= plan.description %>
              </div>
              <% workouts = Workout.where(workout_plan_id: plan.id) %>
              <% completed_count =  CompletedWorkout.where(workout_id: workouts) %>
              <% follower_amount = Follow.where(workout_plan: plan).length %>
              <% total_workouts = workouts.length * follower_amount %>
              <% if completed_count.length == 0 || follower_amount == 0 %>
                <% completed_percentage = "0" %>
              <% else %>
                <% completed_percentage = (1.0 * completed_count.length/total_workouts * 100).round(0) %>
              <% end %>
              <div class="plan-stats">
                <div class="plan-stat-info-container">
                  <div class="plan-stat-info-number"><%= workouts.length %></div>
                  <div class="plan-stat-info-title">Workouts</div>
                </div>
                <div class="plan-stat-info-container">
                  <div class="plan-stat-info-number"><%= completed_percentage %>%</div>
                  <div class="plan-stat-info-title">Completion Rate</div>
                </div>
                <div class="plan-stat-info-container">
                  <div class="plan-stat-info-number"><%= follower_amount %></div>
                  <div class="plan-stat-info-title">Followers</div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="split-container">
      <% @workout_plans.reverse.each do |plan| %>
        <%= link_to workout_plan_workouts_path(plan) do %>
          <div class="plan-container">
            <div class="plan-image">
              <%= image_tag(plan.picture.url) if plan.picture? %>
            </div>
            <div class="plan-content">
              <div class="plan-name">
                <span><%= plan.name %></span>
              </div>
              <div class="plan-description">
                <%= plan.description %>
              </div>
              <% workouts = Workout.where(workout_plan_id: plan.id) %>
              <% completed_count =  CompletedWorkout.where(workout_id: workouts) %>
              <% follower_amount = Follow.where(workout_plan: plan).length %>
              <% total_workouts = workouts.length * follower_amount %>
              <% if completed_count.length == 0 || follower_amount == 0 %>
                <% completed_percentage = "0" %>
              <% else %>
                <% completed_percentage = (1.0 * completed_count.length/total_workouts * 100).round(0) %>
              <% end %>
              <div class="plan-stats">
                <div class="plan-stat-info-container">
                  <div class="plan-stat-info-number"><%= workouts.length %></div>
                  <div class="plan-stat-info-title">Workouts</div>
                </div>
                <div class="plan-stat-info-container">
                  <div class="plan-stat-info-number"><%= completed_percentage %>%</div>
                  <div class="plan-stat-info-title">Completion Rate</div>
                </div>
                <div class="plan-stat-info-container">
                  <div class="plan-stat-info-number"><%= follower_amount %></div>
                  <div class="plan-stat-info-title">Followers</div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/workout_plans/new.html.erb
<%= render 'partials/form' %>

app/views/workout_plans/show.html.erb
<h1><%= @workout_plan.name %></h1>
<p><%= @workout_plan.description %></p>
<p><%= @workout_plan.summary %></p>